net: cnss2: Add cnss_ prefix to wlfw_qdss_trace_start/stop
Add the cnss_ prefix to the wlfw_qdss_trace_start/stop()
functions to avoid conflicts in the global namespace.

ld.lld: error: duplicate symbol: wlfw_qdss_trace_start
>>> defined at qmi.c:1613 (drivers/soc/qcom/icnss2/qmi.c:1613)
>>>            soc/qcom/icnss2/qmi.o:(wlfw_qdss_trace_start) in archive drivers/built-in.a
>>> defined at qmi.c:1430 (drivers/net/wireless/cnss2/qmi.c:1430)
>>>            net/wireless/cnss2/qmi.o:(.text+0x3E2C) in archive drivers/built-in.a

ld.lld: error: duplicate symbol: wlfw_qdss_trace_stop
>>> defined at qmi.c:1619 (drivers/soc/qcom/icnss2/qmi.c:1619)
>>>            soc/qcom/icnss2/qmi.o:(wlfw_qdss_trace_stop) in archive drivers/built-in.a
>>> defined at qmi.c:1436 (drivers/net/wireless/cnss2/qmi.c:1436)
>>>            net/wireless/cnss2/qmi.o:(.text+0x4294) in archive drivers/built-in.a

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>