BUILD: Changing optimization level from -O0 to -O2 to get the drivers building
[Defect / Enhancement / New Feature]

[Problem]
  Build errors observed in rcupdate.h, if broadcom char drivers are built with -O0.
	Error message:
		include/linux/rcupdate.h: In function '__kfree_rcu':
		include/linux/rcupdate.h:822: error: size of array 'type name' is negative

[Solution]
 Changing the optimization level to -O2 will get the drivers building. Needs to find
 a proper fix for this error.

[Reviewers]

[Testing]
    [Test Cases]

    [Label/CL# Synced To]
	mps-lmp-3.0

    [Platform]
	KONA

[BROADCOM INTERNAL NOTES]

Signed-off-by: Sandeepa Prabhu <sprabhu@broadcom.com>