Revert "rpmsg: glink_native: bring in 5.4 changes to wake the bus up"
Revert d2fabd8 ("rpmsg: glink_native: bring in 5.4 changes to wake the bus up").

The reverted commit was an amalgamation of the code around the original
devm_request_irq prior to
b21bd35 ("rpmsg: glink: Use threaded interrupts")
and
f551bd1 ("rpmsg: glink: Request for threaded irq in start phase").
That logic has since been refactored (by those commits), but it is still there.

The reverted commit adds a second request for the same IRQ already requested
by existing code in qcom_glink_native_start but it does so via a different API
and using different flags, leading to the pre-existing IRQ request in
qcom_glink_native_start failing to complete due to IRQ flags mismatch (on top
of other side effects caused by the duplication of the code creating the
device, sending the version, etc).

The qcom_glink_native_start failure causes adsprpcd to never complete its init
procedure, which is retried every 25msecs in an endless loop.

    genirq  : Flags mismatch irq 407. 00006001 (glink-native-adsp) vs. 00004081 (glink-native-adsp)
    ...
    3000000.remoteproc-adsp: glink-edge: failed to request IRQ with -16
    remoteproc1: failed to probe subdevices for 3000000.remoteproc-adsp: -16
    ...
    adsprpcd: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:3426: fastrpc_apps_user_init done
    adsprpcd: vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:41:adsp_default_listener_start called
    adsprpcd: vendor/qcom/proprietary/adsprpc/src/adsp_default_listener.c:67:adsp_default_listener_start started
    adsprpcd: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1437: remote_handle_open: Successfully opened handle 0xffffffff for '":;./\attachguestos on domain 0
    adsprpcd: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:3167: Error 0x200: apps_dev_init failed for domain 0, errno No such device, ioErr -1
    ...
    adsprpcd: vendor/qcom/proprietary/adsprpc/src/adsprpcd.c:53:adsp daemon will restart after 25ms...

As there is no clarity around whether this change was needed in the first
place, revert it in order to restore the previous behaviour, thus fixing the
flags mismatch and adsprpcd init failure loop.

Signed-off-by: Andrea Bernabei <faenil@bernabei.me>