scripts: gcc-wrapper.py: Fix output decoding
This commit presents a refactoring of the GCC output decoding process
within the script. The primary goal of this change remains consistent:
to ensure that bytes strings are correctly handled, preventing them
from being printed as text when processed by the print(line, end=' ')
statement.

In the previous version of the code, decoding was conducted only within
the interpret_warning function, taking place after lines were passed to
the function. This approach was functional, but it had a critical issue:
it resulted in bytes strings being incorrectly interpreted as text when
printed using print(line, end=' ').

In this updated version, we've adjusted the decoding process. Now,
decoding is performed immediately after reading each line from the
proc.stderr stream, using line.decode(), before passing the decoded
bytes string to the interpret_warning function. This ensures that when
the print(line, end=' ') statement is executed, it correctly displays
the decoded string.

Moreover, this refactor also brings attention to an important aspect:
bytes string handling. By ensuring that decoding is performed at the
point of input, we prevent the incorrect interpretation of bytes strings
as text in the GCC output. This correction ensures the accuracy of the
displayed output when utilizing the print(line, end=' ') statement.

This change does not affect the core functionality of the code.

Before:
b"init/main.c:187:2: error: use of undeclared identifier 'force_compilation_fail'\n" b'
        force_compilation_fail\n' b'        ^\n'
b'1 error generated.\n' make[2]: *** [scripts/Makefile.build:288: init/main.o] Error 1
make[1]: *** [Makefile:1841: init] Error 2

After:
init/main.c:187:2: error: use of undeclared identifier 'force_compilation_fail'
         force_compilation_fail
         ^
 1 error generated.

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>