tulip: defconfig: remove ext3 config
follow the other opendevices

apart from that, fix: since somewhere along the way we have:

In file included from ../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd.h:247:0,
                 from ../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/fs/ext3/ext3.h:23,
                 from ../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/fs/ext3/balloc.c:16:
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h: In function 'jbd_lock_bh_state':
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h:18:16: error: 'BH_State' undeclared (first use in this function)
  bit_spin_lock(BH_State, &bh->b_state);
                ^
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h:18:16: note: each undeclared identifier is reported only once for each function it appears in
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h: In function 'jbd_trylock_bh_state':
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h:23:26: error: 'BH_State' undeclared (first use in this function)
  return bit_spin_trylock(BH_State, &bh->b_state);
                          ^
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h: In function 'jbd_is_locked_bh_state':
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h:28:28: error: 'BH_State' undeclared (first use in this function)
  return bit_spin_is_locked(BH_State, &bh->b_state);
                            ^
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h: In function 'jbd_unlock_bh_state':
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h:33:18: error: 'BH_State' undeclared (first use in this function)
  bit_spin_unlock(BH_State, &bh->b_state);
                  ^
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h: In function 'jbd_lock_bh_journal_head':
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h:38:16: error: 'BH_JournalHead' undeclared (first use in this function)
  bit_spin_lock(BH_JournalHead, &bh->b_state);
                ^
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h: In function 'jbd_unlock_bh_journal_head':
../../../../../../../../../../mnt/users/jenkins/workspace/marshmallow/mm-6.0/kernel/sony/msm/include/linux/jbd_common.h:43:18: error: 'BH_JournalHead' undeclared (first use in this function)

Change-Id: I036121096d40222a9c77111a496fd9b034e09cc4
Signed-off-by: Erik Castricum <erikcas1972@gmail.com>