soc: qcom: qmi_rmnet: Add <linux/icmpv6.h> header
After the change in https://source.codeaurora.org/quic/la/kernel/msm-4.14/commit/?h=aosp-new/android-4.14-stable&id=372fb8e270446213ba51b11bfaa7b9632c0efa90 ("net: icmp: pass zeroed opts from icmp{,v6}_ndo_send before sending")
(included in 4.14.223) we need to explicitely add <linux/icmpv6.h>
to use the 'icmp6_hdr' struct because that commit removed the transitive
header inclusion.

Building was failing like this:

    drivers/soc/qcom/qmi_rmnet.c:838:7: error: implicit declaration of function 'icmp6_hdr' [-Werror,-Wimplicit-function-declaration]
    drivers/soc/qcom/qmi_rmnet.c:838:7: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]

Signed-off-by: Pablo Mendez Hernandez <pablomh@gmail.com>