msm: dsps: Refer the local "timer.h" and not from standard search path
Fixes following compilation error:
msm_dsps.c:42:19: error: timer.h: No such file or directory

Signed-off-by: Trilok Soni <tsoni@codeaurora.org>
(cherry picked from commit 4219745c5bad107f2ee46f968f4fedeea2c58604)

Change-Id: I3eed853099743f7155433cee09627569ce96f2b7
Signed-off-by: Zhoulu Luo <zluo@codeaurora.org>